[".config/base16-shell"]
  type = "archive"
  url = "https://github.com/chriskempson/base16-shell/archive/master.tar.gz"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".config/base16-fzf"]
  type = "archive"
  url = "https://github.com/fnune/base16-fzf/archive/refs/heads/master.zip"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"
[".dir_colors"]
  type = "file"
  url = "https://raw.githubusercontent.com/arcticicestudio/nord-dircolors/develop/src/dir_colors"
  refreshPeriod = "168h"
